Vagrant.configure("2") do |config|
  
  # focal64 - ubuntu 20.04
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20240821.0.1"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "my_vm"
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "./services", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL

end
